[FIX] vcp_management
set kind field required at platform level. It doesn't makes sense to have a plateform without kind + it makes failing call of update_information
AttributeError: 'vcp.platform' object has no attribute '_update_information_False'. Did you mean: '_update_information_github'?